name: CI/CD Workflow (Staging)

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend with Maven
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Remove .gitmodules if exists
        run: |
          if [ -f .gitmodules ]; then
            echo ".gitmodules found. Removing it..."
            rm .gitmodules
            git rm --cached .gitmodules || true
          else
            echo "No .gitmodules file found."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Updated to Node.js 20 for react-router-dom v7 compatibility
          
      - name: Install frontend dependencies
        run: npm install  # Removed working-directory as it appears the app is in the root

      - name: Build React App
        run: npm run build

      - name: Run frontend tests
        run: |
          # Install Jest dependencies for testing
          npm install --save-dev jest-dom @testing-library/react
          npm test -- --watchAll=false