name: CI/CD Workflow (Staging)

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend with Maven
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          always-auth: false

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build React App
        working-directory: client
        run: npm run build

      - name: Run client tests
        working-directory: client
        run: npm test -- --watchAll=false
