name: CI/CD Workflow (Staging)

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend with Maven
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend # Assure que le backend est construit avant le frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      # Mise à jour du commentaire pour refléter le nouveau nom
      - name: Remove .gitmodules if exists
        run: |
          if [ -f .gitmodules ]; then
            echo ".gitmodules found. Removing it..."
            rm .gitmodules
            git rm --cached .gitmodules || true
          else
            echo "No .gitmodules file found."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Utiliser Node.js 18 (LTS)
          always-auth: false

      # Modification : Utilisation de "npm install" au lieu de "npm ci"
      - name: Install frontend dependencies
        working-directory: frontend # Assurez-vous que le dossier est bien 'frontend'
        run: npm install # <--- MODIFICATION ICI

      - name: Build React App
        working-directory: frontend # Assurez-vous que le dossier est bien 'frontend'
        run: npm run build

      - name: Run frontend tests
        working-directory: frontend # Assurez-vous que le dossier est bien 'frontend'
        run: npm test -- --watchAll=false